version: '3.9'

services:
  client:
    build:
      context: ./client
    ports:
      - 5173:5173
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - dist:/app/dist
  
  server:
    build:
      context: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/app/src
      - dist:/app/client/dist
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db
    command: npm run dev
  
  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dist:
  db-data:
