version: '3.9'

services:
  client:
    build:
      context: ./client
    ports:
      - 3000:5173
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - dist:/app/dist
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=1337
  
  server:
    build:
      context: ./server
    ports:
      - 1337:1337
    volumes:
      - ./server/src:/app/src
      - dist:/app/client/dist
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
      - HOST=0.0.0.0
      - PORT=1337
    depends_on:
      - db
    command: npm run dev
  
  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dist:
  db-data:
